services:
  web:
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    env_file:
      - .env.staging
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.staging
    volumes:
      - static_files:/app/staticfiles
    restart: always

  db:
    env_file:
      - .env.staging
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf
      - static_files:/app/staticfiles
    depends_on:
      - web
    restart: always

volumes:
  static_files:
